#!/usr/bin/env bash
# Configure localhost and facebook.com entries in /etc/hosts.
sed 's/127.0.0.1/127.0.0.2/' /etc/hosts > /tmp/hosts
cat /tmp/hosts > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
